# Generated by Django 3.2.9 on 2021-11-06 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strings',
            options={'ordering': ['createdAt']},
        ),
    ]
