# Generated by Django 3.2.9 on 2021-11-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_strings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strings',
            options={},
        ),
    ]
